version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    groups:
      cargo-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: cargo
    directory: /fuzz
    schedule:
      interval: weekly
      day: tuesday
    groups:
      fuzz-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: tuesday
